#! /bin/bash

# Make sure we're on Fedora 14
if [ $(cat /etc/redhat-release | grep "Fedora release 14" | wc -l) == 0 ];then
    echo "Sorry, this script is only for Fedora 14"
    exit
fi

# Get root permissions if we don't have them
if [ $(whoami) != "root" ];then
    echo "I need root privileges, please."
    su -c "$0"
    exit
fi

# Dependencies for GitBox
yum -y install python-inotify screen

# Dependencies for compiling patched Git
yum -y install git python-devel curl-devel expat-devel perl-ExtUtils-MakeMaker zlib-devel openssl-devel gcc make

# Patch and compile Git as "Get"
rm -rfv /opt/get
git clone git://git.kernel.org/pub/scm/git/git.git /tmp/gitcustom
cd /tmp/gitcustom
git checkout v1.7.3.2
find . -name '*.c' -type f -exec sed -i 's/\.git\([\"\/]\)/\.get\1/g' {} \;
find . -name '*.h' -type f -exec sed -i 's/\.git\([\"\/]\)/\.get\1/g' {} \;
find . -name '*.c' -type f -exec sed -i 's/\.gitignore/\.getignore/g' {} \;
find . -name '*.c' -type f -exec sed -i "s/!= 'i')/!= 'e')/g" {} \;
make prefix=/opt/get
make install prefix=/opt/get
cd ~
rm -rfv /tmp/gitcustom

# Increase maximum inotify subscriptions
echo 1000000 | tee /proc/sys/fs/inotify/max_user_watches
echo "echo 1000000 | tee /proc/sys/fs/inotify/max_user_watches" >> /etc/rc.local

# Cloning the remote GitBox
echo -e "\n\n\n----NEXT STEPS----\n\n\nOn a server, create a directory (maybe ~/GitBox/), cd into that directory,
and run:\ngit --bare init\n\nMake sure you have public key authentication working from your machine to the
server. When you are done with that step, enter the clone URL to your GitBox repository below (ex:
ssh://username@hostname:port/path/to/GitBox):\n\n"
echo -n "Please enter the clone URL for your GitBox: " 
read gitbox
echo -n "Please enter the local path for your GitBox (ex: /srv/gitbox): "
read localgitbox
/opt/get/bin/git clone $gitbox $localgitbox
chown -R $USERNAME:$USERNAME $localgitbox

echo -e "\n\n\n----INSTALLATION COMPLETE----\n\n\nYou can now start the daemon using the provided init script."
